version: '2.4'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./shared:/shared
    networks:
      - blockchain-net
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  blockchain-net:
    driver: bridge