version: '2.4'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/src
    networks:
      - blockchain-net

networks:
  blockchain-net:
    driver: bridge