version: '2.29.7'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./shared:/shared
    networks:
      - blockchain-net
  
  internal-node:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./shared:/shared
    networks:
      - blockchain-net


networks:
  blockchain-net:
    driver: bridge